// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ksEoxA5nNk_0YyeVx7e9bh7j7hJASdQ',
    appId: '1:820635568957:web:af0d451df4d065c8105354',
    messagingSenderId: '820635568957',
    projectId: 'futsal-book-app',
    authDomain: 'futsal-book-app.firebaseapp.com',
    storageBucket: 'futsal-book-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZhByu73iHe2HilHqunqQxb_Vv4kKkH1E',
    appId: '1:820635568957:android:e801e37eaee3feee105354',
    messagingSenderId: '820635568957',
    projectId: 'futsal-book-app',
    storageBucket: 'futsal-book-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrVIdR_-laYV-ZBAMarR12AnW0ezWPpnc',
    appId: '1:820635568957:ios:66795916ea746a07105354',
    messagingSenderId: '820635568957',
    projectId: 'futsal-book-app',
    storageBucket: 'futsal-book-app.appspot.com',
    iosClientId: '820635568957-ftskgjk59v7h92htn7pu9qid6kam2ajn.apps.googleusercontent.com',
    iosBundleId: 'com.futsalnook.futsalBookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrVIdR_-laYV-ZBAMarR12AnW0ezWPpnc',
    appId: '1:820635568957:ios:e65c80c0764a691a105354',
    messagingSenderId: '820635568957',
    projectId: 'futsal-book-app',
    storageBucket: 'futsal-book-app.appspot.com',
    iosClientId: '820635568957-ioap5oa5a2ih4f8bsc96l8gos6i0o3o2.apps.googleusercontent.com',
    iosBundleId: 'com.futsalnook.futsalBookApp.RunnerTests',
  );
}
